version: "3.9"
services:
  postgres:
    container_name: postgres
    image: "postgres:13.2"
    volumes:
      - ./db-data:/var/lib/postgresql/data/
      - ./sql:/docker-entrypoint-initdb.d/:ro
    env_file:
      - ./database.dev.env
    ports:
      - "5432:5432"
    networks:
      - backend
 

  apache:
    container_name: web_server
    build: ./apache-auth
    depends_on:
      - keycloak
    ports:
      - "8000:8000"
    networks:
      - frontend
    

  keycloak:
    container_name: keycloak
    image: "jboss/keycloak:15.0.2"
    env_file:
      - ./keycloak.dev.env
    depends_on:
      - "postgres"
    ports:
      - "8180:8080"
      - "8787:8787" # debug port
    networks:
      - backend
      - frontend

networks:
  backend:
    name: backend
    driver: bridge
  frontend:
    name: frontend
    driver: bridge
  
