version: "3.9"
services:
  postgres:
    container_name: postgres
    image: "postgres:13.2"
    volumes:
      - ./db-data:/var/lib/postgresql/data/
      - ./sql:/docker-entrypoint-initdb.d/:ro
    env_file:
      - ./database.dev.env
    ports:
      - "5432:5432"
    networks:
      - backend
 
  nginx:
    container_name: web_page
    #build: ./nginx-server
    image: nginx:stable-perl
    depends_on:
      - keycloak
    volumes: 
      - ./auth:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "5050:80"
    networks:
      - frontend

  keycloak:
    container_name: keycloak
    image: "jboss/keycloak:15.0.2"
    env_file:
      - ./keycloak.dev.env
    depends_on:
      - "postgres"
    ports:
      - "8180:8080"
      - "8787:8787" # debug port
    networks:
      - backend
      - frontend

networks:
  backend:
    name: backend
    driver: bridge
  frontend:
    name: frontend
    driver: bridge
  
