version: "3.9"
services:

  postgres:
    container_name: postgres
    image: "postgres:13.2"
    volumes:
      - ./db-data:/var/lib/postgresql/data/
      - ./sql:/docker-entrypoint-initdb.d/:ro
    env_file:
      - ./database.dev.env
    ports:
      - "5432:5432"
    networks:
      backend:
        ipv4_address: 10.15.0.4
      

  node:
    container_name: node_server
    build: ./node
    depends_on:
      - keycloak
    ports:
      - "3000:3000"
    networks:
      frontend:
        ipv4_address: 10.25.0.4
      

  keycloak:
    container_name: keycloak
    image: "jboss/keycloak:15.0.2"
    env_file:
      - ./keycloak.dev.env
    depends_on:
      - "postgres"
    ports:
      - "8080:8080"
      - "8787:8787" # debug port
    networks:
      backend:
        ipv4_address: 10.15.0.2
      frontend:
        ipv4_address: 10.25.0.2
    

        

networks:
  backend:
    name: backend
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.15.0.0/16

  frontend:
    name: frontend
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.25.0.0/16
  
